spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      propreties:
        hibernate.format.sql: true

        loggin:
          level:
            org:
              hibernate:
                type: trace